version: "3.8"
services:
    app:
        build:
            context: ./clsapp
            dockerfile: ./Dockerfile
        user: "serv"
        working_dir: /app
        command: ["./wait-for/wait-for", "learnapp:18090", "--", "./clsapp"]
        depends_on:
            - db
        volumes:
            - imagedata:/cls/images
            - modeldata:/cls/models
        ports:
            - "18080:18080"
        networks:
            - cls-net
    learnapp:
        build:
            context: ./learnapp
            dockerfile: ./Dockerfile
        user: "serv"
        working_dir: /app
        volumes:
            - imagedata:/cls/images
            - modeldata:/cls/models
        ports:
            - "18090:18090"
        networks:
            - cls-net
    db:
        image: mysql
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --lower_case_table_names=0
        environment:
            MYSQL_ROOT_PASSWORD: "password0"
            MYSQL_DATABASE: "cls_image_db"
            MYSQL_USER: "user1"
            MYSQL_PASSWORD: "password1"
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "18100:3306"
        networks:
            - cls-net

volumes:
    dbdata:
    imagedata:
    modeldata:

networks:
    cls-net:
        driver: bridge
